[build]
builder = "nixpacks"
buildCommand = "cd 'Online Book Festival/backend' && npm install"

[deploy]
startCommand = "cd 'Online Book Festival/backend' && npm start"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[service]
root_directory = "Online Book Festival/backend"